version: '3.1'
services:
  web:
    image: sweun2/paperplane-server-api:paperplane
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/paperplane
      SPRING_DATASOURCE_USERNAME: paperplane
      SPRING_DATASOURCE_PASSWORD: paperplane
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - kibana
    restart: always
    ports:
      - "8080:8080"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: paperplane
      MYSQL_ROOT_PASSWORD: paperplane
      MYSQL_USER: paperplane
      MYSQL_PASSWORD: paperplane
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.4
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
    volumes:
      - elasticsearchvolume
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Seoul
    user: root
    restart: always
    privileged: true
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.0
    ports:
      - 5601:5601
    networks:
      - default
    environment:
      ELASTICSERCH_UTL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      TZ: Asia/Seoul
    restart: always
    privileged: true

