version: '3.1'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: paperplane
      MYSQL_ROOT_PASSWORD: paperplane
      MYSQL_USER: paperplane
      MYSQL_PASSWORD: paperplane
